spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DEV_DB_URL:jdbc:oracle:thin:@//localhost:1521/XEPDB1}
    username: ${DEV_DB_USERNAME:L2D}
    password: ${DEV_DB_PASSWORD:fullstackl2d}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${DEV_JWT_SECRET:thisisaverylongsecretkeyforjwtgeneration123456original}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
