spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

jwt:
  # Switch to asymmetric signing in prod
  private-key: ${JWT_PRIVATE_KEY:classpath:keys/private.pem}
  public-key: ${JWT_PUBLIC_KEY:classpath:keys/public.pem}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
      roles: ACTUATOR_ADMIN
