spring:
  config:
    activate:
      on-profile: prod

  # Optional: secure Eureka dashboard
  security:
    user:
      name: eureka
      password: ${EUREKA_PASSWORD:secret}

eureka:
  server:
    enableSelfPreservation: true    # keep safe in prod

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus   # minimal in prod
  endpoint:
    health:
      show-details: when_authorized
      roles: ACTUATOR_ADMIN
