spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:oracle:thin:@//oracle-db:1521/XEPDB1
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  public-key: ${JWT_PUBLIC_KEY:classpath:keys/public.pem}
